### ISSUE TITLE
预测结果不对

### ISSUE THREAD

**Issue by immarioo** [ouyanghuiyu/centernet_mobilenetv2_ncnn#8]
请问下作者是使用的哪个版本的centernet训练的呀？
https://github.com/xingyizhou/CenterNet 是这个吗？

**Comment by immarioo** [comment]
我感觉是不同版本的centernet的后处理方式不同，解析网络输出decode的实现不一样导致的。

**Comment by immarioo** [comment]
搞定了，感谢。

**Comment by FightStone** [comment]
@wanglaotou 您好，我可视化出了中心点的位置挺准的，但为什么矩形框的长和宽不准，请问是前后处理的有问题吗？请您指点下，谢谢。
